id: A89F9C143
title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the Supreme
  Tulku of the Mañjughoṣa Guru'
type: translation
pechas:
- IB5E0D864
- I7B88BC3B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:48:00.851761
  last_modified_at: 2023-01-04 12:48:00.851782
  collections:
  - Katok Situ Chökyi Gyatso Series
  - Works of Tibetan Masters
alignment_to_base:
  IB5E0D864/8C56: C5C1
  I7B88BC3B/4A0D: C5C1
